name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Replace '3.x' with your desired Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Replace with your package manager and dependencies

    - name: Run tests
      run: |
        pytest  # Replace with your testing command
